apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonAnnotations:
  app.kubernetes.io/name: argocd
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/instance: argocd
  app.kubernetes.io/part-of: argocd
  app.kubernetes.io/environment: grn

commonLabels:
  environment: grn
  owenr: engineering

patchesJSON6902:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: helm-platform
    patch: |
      - op: replace
        path: /spec/generators/0/git/files/0/path
        value: "platform/**/grn.yaml"
