apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonAnnotations:
  app.kubernetes.io/name: argocd
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/instance: argocd
  app.kubernetes.io/part-of: argocd
  app.kubernetes.io/environment: grn

commonLabels:
  environment: grn
  owner: engineering

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: helm-applications
    patch: |
      - op: replace
        path: /spec/generators/0/matrix/generators/0/git
        value:
          repoURL: https://github.com/gambol99/eks-services.git
          revision: HEAD
          files:
            - path: applications/**/grn.yaml
      - op: replace
        path: /spec/generators/0/matrix/generators/1/list/elements/0
        value:
          environment: grn
          repository: https://github.com/gambol99/eks-services.git
          revision: HEAD

  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: helm-platform
    patch: |
      - op: replace
        path: /spec/generators/0/matrix/generators/0/git
        value:
          repoURL: https://github.com/gambol99/eks-services.git
          revision: HEAD
          files:
            - path: platform/**/grn.yaml
      - op: replace
        path: /spec/generators/0/matrix/generators/1/list/elements/0
        value:
          environment: grn
          repository: https://github.com/gambol99/eks-services.git
          revision: HEAD

  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: kustomize-applications
    patch: |
      - op: replace
        path: /spec/generators/0/matrix/generators/1/list/elements/0
        value:
          environment: grn
          repository: https://github.com/gambol99/eks-services.git
          revision: HEAD
      - op: replace
        path: /spec/generators/0/selector/matchExpressions/0/key
        value: kustomize.revisions.grn
      - op: replace
        path: /spec/generators/1/matrix/generators/1/list/elements/0
        value:
          environment: grn
          repository: https://github.com/gambol99/eks-services.git
          revision: HEAD
      - op: replace
        path: /spec/generators/1/selector/matchExpressions/1/key
        value: kustomize.environments.grn

  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: kustomize-platform
    patch: |
      - op: replace
        path: /spec/generators/0/matrix/generators/1/list/elements/0
        value:
          environment: grn
          repository: https://github.com/gambol99/eks-services.git
          revision: HEAD
      - op: replace
        path: /spec/generators/0/selector/matchExpressions/0/key
        value: kustomize.revisions.grn
      - op: replace
        path: /spec/generators/1/matrix/generators/1/list/elements/0
        value:
          environment: grn
          repository: https://github.com/gambol99/eks-services.git
          revision: HEAD
      - op: replace
        path: /spec/generators/1/selector/matchExpressions/1/key
        value: kustomize.environments.grn
