apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonAnnotations:
  app.kubernetes.io/name: argocd
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/instance: argocd
  app.kubernetes.io/part-of: argocd
  app.kubernetes.io/environment: grn

commonLabels:
  environment: grn
  owner: engineering

patches:
  - target:
      group:
      version: v
      kind: Secret
      name: in-cluster
    patch: |
      - op: replace
        path: /metadata/annotations/environment
        value: grn
      - op: replace
        path: /metadata/annotations/repository
        value: https://github.com/gambol99/eks-services.git
      - op: replace
        path: /metadata/annotations/revision
        value: HEAD

  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: helm-applications
    path: applications.json

  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: helm-platform
    path: platform.json

  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: kustomize-applications
    path: applications.json

  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: kustomize-platform
    path: platform.json
