---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications-helm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  goTemplate: true
  ## Add a strategy that will only sync the resources that have changed
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: phase
              operator: In
              values:
                - primary
        - matchExpressions:
            - key: phase
              operator: In
              values:
                - secondary
        - matchExpressions:
            - key: phase
              operator: NotIn
              values:
                - primary
                - secondary

  # Generate applications from the shared services repository
  generators:
    - merge:
        mergeKeys:
          - chart
        generators:
          - git:
              repoURL: https://github.com/gambol99/eks-services.git
              revision: HEAD
              files:
                - path: applications/**/helm.yaml
          - list:
              elements:
                - environment: grn
                  repository: https://github.com/gambol99/eks-services.git
                  revision: HEAD
      selector:
        matchExpressions:
          - key: helm.enable
            operator: In
            values: ["true"]
          - key: helm.chart
            operator: Exists

  ## Template out an application for each of the tenant applications
  template:
    metadata:
      name: "applications-{{.path.basenameNormalized}}"
      namespace: argocd
      labels:
        phase: '{{default "tertiary" .sync.phase}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io

    spec:
      project: applications
      sources:
        - repoURL: "{{.helm.repository}}"
          targetRevision: "{{.helm.version}}"
          chart: "{{.helm.chart}}"
          helm:
            releaseName: "{{default .path.basenameNormalized .helm.releaseName}}"
            valueFiles:
              - "$values/{{.path.basename}}/defaults.yaml"
              - "$values/{{.path.basename}}/{{.environment}}.yaml"
            ignoreMissingValueFiles: true

      ## Destination is the cluster to deploy to
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.helm.namespace}}"

      ## Sync policy for the application
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        # Use server-side apply for better efficiency and interop
        # between controllers making partial changes to manifests.
        # Also enable apply out of sync only rather than trying to
        # apply all resources in the application.
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - ApplyOutOfSyncOnly=true
