---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-kustomize
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  goTemplate: true
  ## Add a strategy that will only sync the resources that have changed
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: phase
              operator: In
              values:
                - primary
        - matchExpressions:
            - key: phase
              operator: In
              values:
                - secondary
        - matchExpressions:
            - key: phase
              operator: NotIn
              values:
                - primary
                - secondary
  # Generate applications from the shared services repository
  generators:
    - merge:
        mergeKeys:
          - name
        generators:
          - git:
              repoURL: https://github.com/gambol99/eks-services.git
              revision: HEAD
              files:
                - path: platform/**/kustomize.yaml
          - list:
              elements:
                - environment: grn
                  repository: https://github.com/gambol99/eks-services.git
                  revision: HEAD
      selector:
        matchExpressions:
          - key: kustomize.enable
            operator: In
            values: ["true"]
          - key: kustomize.namespace
            operator: Exists
          - key: kustomize.name
            operator: Exists
  ## Template out an application for each of the tenant applications
  template:
    metadata:
      name: "{{.path.basenameNormalized}}"
      namespace: argocd
      labels:
        phase: '{{default "tertiary" .sync.phase}}'
        environment: "{{.environment}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: platform
      source:
        repoURL: "{{.repository}}"
        targetRevision: "{{.revision}}"
        path: "{{ .path.path }}/overlays/{{.environment}}/kustomization.yaml"
        kustomize: {} # Enables Kustomize for this application
      ## Destination is the cluster to deploy to
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.kustomize.namespace}}"
      ## Sync policy for the application
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        # Use server-side apply for better efficiency and interop
        # between controllers making partial changes to manifests.
        # Also enable apply out of sync only rather than trying to
        # apply all resources in the application.
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - ApplyOutOfSyncOnly=true
