---
apiVersion: v1
kind: Secret
metadata:
  name: in-cluster
  namespace: argocd
  annotations:
    environment: change_me
    repository: change_me
    revision: change_me
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: in-cluster
  server: https://kubernetes.default.svc
