apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  sourceGit: https://github.com/gambol99/eks-services

resources:
  - credentials.yaml
  - projects.yaml
  #  - platform-helm.yaml
  #  - platform-kustomize.yaml
  # - application-helm.yaml
  - helm-platform.yaml
  #- application-kustomize.yaml
