---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kustomize-platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  goTemplate: true

  ## Add a strategy that will only sync the resources that have changed
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: phase
              operator: In
              values:
                - primary
        - matchExpressions:
            - key: phase
              operator: In
              values:
                - secondary
        - matchExpressions:
            - key: phase
              operator: NotIn
              values:
                - primary
                - secondary

  # Generate applications from the shared services repository
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/gambol99/eks-services.git
              revision: HEAD
              files:
                - path: "platform/**/kustomize.yaml"
          - list:
              elements:
                - environment: grn
                  repository: https://github.com/gambol99/eks-services.git
                  revision: HEAD
      ## Filter on only those files with the correct values
      selector:
        matchExpressions:
          - key: kustomize.enable
            operator: In
            values: ["true"]

  ## Template out an application for each of the tenant applications
  template:
    metadata:
      name: "platform-{{ .path.basenameNormalized }}"
      namespace: argocd
      labels:
        app.kubernetes.io/name: argocd
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/instance: argocd
        app.kubernetes.io/part-of: argocd
        app.kubernetes.io/environment: "{{ .environment }}"
        app.kubernetes.io/type: kustomize
        phase: '{{ default "tertiary" .sync.phase }}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io

    spec:
      project: applications
      source:
        repoURL: "{{ default .repository .kustomize.repository }}"
        targetRevision: "{{ default .revision .kustomize.revision }}"
        path: "{{ .path.path }}/overlays/{{ .environment }}"
        kustomize: {}

      ## Destination is the cluster to deploy to
      destination:
        server: https://kubernetes.default.svc
        ## /applications/[1]/DIRECTORY/FILE.yaml
        namespace: "{{ index .path.segments 1 }}"

      ## Sync policy for the application
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        # Use server-side apply for better efficiency and interop
        # between controllers making partial changes to manifests.
        # Also enable apply out of sync only rather than trying to
        # apply all resources in the application.
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - ApplyOutOfSyncOnly=true
