apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonAnnotations:
  app.kubernetes.io/name: argocd
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/instance: argocd
  app.kubernetes.io/part-of: argocd
  app.kubernetes.io/environment: yel

commonLabels:
  environment: yel
  owner: engineering

patches:
  - target:
      group:
      version: v1
      kind: Secret
      name: in-cluster
    patch: |
      - op: replace
        path: /metadata/annotations/environment
        value: grn
      - op: replace
        path: /metadata/annotations/repository
        value: https://github.com/gambol99/eks-services.git
      - op: replace
        path: /metadata/annotations/revision
        value: HEAD

  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: helm-applications
    patch: |
      - op: replace
        path: /spec/generators/0/git
        value:
          repoURL: https://github.com/gambol99/eks-services.git
          revision: HEAD
          files:
            - path: applications/**/yel.yaml
          values:
            environment: yel
            repository: https://github.com/gambol99/eks-services.git
            revision: HEAD

  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: helm-platform
    patch: |
      - op: replace
        path: /spec/generators/0/git
        value:
          repoURL: https://github.com/gambol99/eks-services.git
          revision: HEAD
          files:
            - path: platform/**/yel.yaml
          values:
            environment: yel
            repository: https://github.com/gambol99/eks-services.git
            revision: HEAD

  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: kustomize-applications
    patch: |
      - op: replace
        path: /spec/generators/0/git
        value:
          repoURL: https://github.com/gambol99/eks-services.git
          revision: HEAD
          files:
            - path: applications/**/kustomize.yaml
          values:
            environment: yel
            repository: https://github.com/gambol99/eks-services.git
            revision: HEAD
      - op: replace
        path: /spec/generators/0/selector/matchExpressions/0/key
        value: kustomize.revisions.yel

      - op: replace
        path: /spec/generators/1/git
        value:
          repoURL: https://github.com/gambol99/eks-services.git
          revision: HEAD
          files:
            - path: applications/**/kustomize.yaml
          values:
            environment: yel
            repository: https://github.com/gambol99/eks-services.git
            revision: HEAD
      - op: replace
        path: /spec/generators/1/selector/matchExpressions/1/key
        value: kustomize.environments.yel

  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: kustomize-platform
    patch: |
      - op: replace
        path: /spec/generators/0/git
        value:
          repoURL: https://github.com/gambol99/eks-services.git
          revision: HEAD
          files:
            - path: applications/**/kustomize.yaml
          values:
            environment: yel
            repository: https://github.com/gambol99/eks-services.git
            revision: HEAD
      - op: replace
        path: /spec/generators/0/selector/matchExpressions/0/key
        value: kustomize.revisions.yel

      - op: replace
        path: /spec/generators/1/git
        value:
          repoURL: https://github.com/gambol99/eks-services.git
          revision: HEAD
          files:
            - path: applications/**/kustomize.yaml
          values:
            environment: yel
            repository: https://github.com/gambol99/eks-services.git
            revision: HEAD
      - op: replace
        path: /spec/generators/1/selector/matchExpressions/1/key
        value: kustomize.environments.yel
